services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\ApiBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'

    _instanceof:
        A2Global\A2Platform\Bundle\ApiBundle\Handler\ApiRequestHandlerInterface:
            tags: [ 'a2platform.api.handler.request' ]

    A2Global\A2Platform\Bundle\ApiBundle\Registry\ApiRequestHandlerRegistry:
        arguments:
            - !tagged_iterator a2platform.api.handler.request