services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\ApiBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'

    _instanceof:
        A2Global\A2Platform\Bundle\ApiBundle\Provider\Route\ApiRouteProviderInterface:
            tags: [ 'a2platform.api.provider.route' ]

    A2Global\A2Platform\Bundle\ApiBundle\Registry\ApiRouteProviderRegistry:
        arguments:
            - !tagged_iterator a2platform.api.provider.route