a2platform_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /
a2platform_auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /
a2platform_core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /