security:
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: A2Global\A2Platform\Bundle\AuthBundle\Security\LoginFormAuthenticator
            logout:
                path: authentication_logout
                target: app_default
