services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\DatasheetBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Utility/'
            - '../src/Component/'

    # move to data bundle as provider
    A2Global\A2Platform\Bundle\DatasheetBundle\Builder\DatasheetBuilder:
        arguments:
            $dataReaders: !tagged_iterator a2platform.data.reader
