services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\DatasheetBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Utility/'
            - '../src/Component/'

    _instanceof:
        A2Global\A2Platform\Bundle\DatasheetBundle\Filter\DatasheetFilterInterface:
            tags: [ 'a2platform.datasheet.filter' ]

    A2Global\A2Platform\Bundle\DatasheetBundle\Registry\DatasheetFilterRegistry:
        arguments:
            - !tagged_iterator a2platform.datasheet.filter
