services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\DataBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Component/'
            - '../../Entity/'

    _instanceof:
        A2Global\A2Platform\Bundle\DataBundle\Reader\DataReaderInterface:
            tags: [ 'a2platform.data.reader' ]
        A2Global\A2Platform\Bundle\DataBundle\FilterApplier\FilterApplierInterface:
            tags: [ 'a2platform.data.filter_applier' ]

    A2Global\A2Platform\Bundle\DataBundle\Registry\DataReaderRegistry:
        arguments:
            - !tagged_iterator a2platform.data.reader
    A2Global\A2Platform\Bundle\DataBundle\Registry\FilterApplierRegistry:
        arguments:
            - !tagged_iterator a2platform.data.filter_applier