services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\PlatformBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Component/'
            - '../../Entity/'

    A2Global\A2Platform\Bundle\PlatformBundle\Registry\DataReaderRegistry:
        arguments:
            - !tagged_iterator a2platform.data.reader

    A2Global\A2Platform\Bundle\PlatformBundle\Registry\TwigBlockRegistry:
        arguments:
            - !tagged_iterator a2platform.twig.block

    A2Global\A2Platform\Bundle\PlatformBundle\Registry\FilterApplierRegistry:
        arguments:
            - !tagged_iterator a2platform.data.filter_applier
