services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\PlatformBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Component/'
            - '../../Entity/'