twig:
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: name

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
#            sluggable: false