services:
    _defaults:
        autowire: true
        autoconfigure: true

    A2Global\A2Platform\Bundle\CoreBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Utility/'

    _instanceof:
        A2Global\A2Platform\Bundle\CoreBundle\Handler\Response\ResponseHandlerInterface:
            tags: [ 'a2platform.core.handler.response' ]

    A2Global\A2Platform\Bundle\CoreBundle\Builder\ResourceRequestBuilder:
        bind:
            $formTypes: !tagged form.type

    A2Global\A2Platform\Bundle\CoreBundle\Registry\ResponseHandlerRegistry:
        bind:
            $services: !tagged a2platform.core.handler.response
